---
# the alter system does not work on extentions parameters
- name: "Changing the pg extentions parameters (that reqiured reload) in postgresql.conf"
  lineinfile:
    path: "{{ pg_data }}/postgresql.conf"
    insertafter: "^(#{{ item.name }}=|#{{ item.name }} =|# {{ item.name }}=|# {{ item.name }} =)"
    regexp: "^({{ item.name }}=|{{ item.name }} =)"
    line: "{{ item.name }} = {{ item.value }}"
  loop: "{{ extentions_info \
            | selectattr('reload_params','defined')\
            | map(attribute='reload_params') \
            | sum(start=[]) }}"
  notify: Reload pg
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"

- name: "Changing the pg extentions parameters (that reqiured restart pg) in postgresql.conf"
  lineinfile:
    path: "{{ pg_data }}/postgresql.conf"
    insertafter: "^(#{{ item.name }}=|#{{ item.name }} =|# {{ item.name }}=|# {{ item.name }} =)"
    regexp: "^({{ item.name }}=|{{ item.name }} =)"
    line: "{{ item.name }} = {{ item.value }}"
  loop: "{{ extentions_info \
            | selectattr('restart_params','defined')\
            | map(attribute='restart_params') \
            | sum(start=[]) }}"
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
  notify: Restart pg 

- name: "Adding the extenstion to the listed databases"
  postgresql_ext:
    name: "{{ item.extention }}"
    db: "{{ item.database }}"
    state: present
  loop: "{{ extentions_info }}"
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
...
