## CHILD PLAY - INSTALL POSTGRESQL STANDALONE ##
- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: no
  tasks:

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: cfg-os-user
      tags: cfg-os-user

    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - name: Initiate Cluster
      command: "/usr/pgsql-{{ pg_major_version }}/bin/initdb --pgdata {{ pg_data }} --data-checksums"
      become_user: "{{ pg_os_user }}"
      tags: initdb

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv

    - import_role: 
        name: cfg-pg-post-inst
      tags: cfg-pg-post-inst

    - import_role:
        name: def-tbs
      tags: def-tbs

#    - name: Adding the extenstions to postrges db
#      postgresql_ext:
#        db: "{{ admin_db_user }}"
#        login_user: "{{ admin_db_user }}"
#        name: "{{ item }}"
#        state: present
#      loop: "{{ extentions }}"
#      become_user: "{{ pg_os_user }}"
#      environment:
#        PGDATA: "{{ pg_data }}"
#      tags:
#        - pg_extentions
      
# postgres standalone automation - 
# 1. install rpms V
# 2. change user definitions - including bash profile V
# 3. prep dirs V
# 4. change systemd postgres service V
# 5. initdb --data-checksums V
# 6. postgresql.conf params V
# 7. pg_hba.conf V
# 8. change postgres password V
# 9. create tablespace V
# 10. adding pg_stat_statement, postgis extentions
# 11. change tablespace of template 1 V
# 12. create database and user according to our permissions module


#
#DEPLOYMENT
#- import playbook - standalone - inventorygroup
#  - role - inst-rpms V
#  - role - config-user V
#  - role - prep-dirs V
#  - task - initdb V
#  - role - config-service V
#  - role - cfg-pg-post-inst hba,pg basic + pass V
#  - role - def-tbs prms,dirs,db-def V

#- import playbook - extentions -  one host - sorted first - master
#  - role - postgis extention
#  - role - pg_stat_statements extention

#
#- import playbook - add app database + app user + permissions one host - sorted first - master
#  - role - cre-app-db-user
#

#- import playbook - replica - inventorygroup - sorted first - master
#  - role - selinux
#  - ?
#  - ?
#  - ?
#  handlers
#  - role - reboot-gracefully
#
