## CHILD PLAY - INSTALL POSTGRESQL STANDALONE ##
- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: no
  tasks:

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: cfg-os-user
      tags: cfg-os-user

    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - name: Initiate Cluster
      command: >
             "/usr/pgsql-{{ pg_major_version }}/bin/initdb
              --pgdata {{ pg_data }} 
              --data-checksums"
      become_user: "{{ pg_os_user }}"
      tags: initdb

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv

    - name: "Getting needed params"
      setup:
        gather_subset: "!all,!min,hardware"
      tags: 
        - effective-cache-size
        - shared-buffers
        - cfg-pg-prms

    - name: "finding the effective cache size recommended"
      set_fact:
        effective_cache_size: "{{ (ansible_memtotal_mb * 0.75)|round|int|string + \"MB\"}}"
      tags:
        - effective-cache-size
        - cfg-pg-prms

    - name: "finding the shared_buffers size recommended "
      set_fact:
        shared_buffers: "{{ [ (ansible_memtotal_mb*0.25)|round|int , max_shared_buffer_size_mb|int ]|min|string + \"MB\" }}"
      tags:
        - shared-buffers
        - cfg-pg-prms

    - name: "adding the specific params to the param list with the standart value"
      set_fact:
        pg_standalone_params: "{{ pg_standalone_params + [ item ] }}"
      when: item.value is defined
      loop:
        - { "name": "shared_buffers", "value": "{{ shared_buffers }}" }
        - { "name":  "effective_cache_size", "value": "{{ effective_cache_size }}" }
      tags:
        - effective-cache-size
        - shared-buffers
        - cfg-pg-prms

    - import_role:
        name: cfg-pg-prms
      vars:
        pg_params: "{{ pg_standalone_params }}"
        pg_hba_params: "{{ pg_hba_standalone_params }}"
      tags: 
        - cfg-pg-prms
        - effective-cache-size
        - shared-buffers

    - import_role:
        name: cfg-pg-prms
      vars:
        pg_params: "{{ pg_stat_statements_params }}"
      when: pg_stat_statements_extenstion|bool
      tags:
        - cfg-pg-prms
        - pg_stat_statements


# postgres standalone automation - 
# 1. install rpms V
# 2. change user definitions - including bash profile V
# 3. prep dirs V
# 4. change systemd postgres service V
# 5. initdb --data-checksums V
# 6. postgresql.conf params V
# 7. pg_hba.conf V
# 8. adding pg_stat_statement, postgis extentions
# 9. change tablespace of template 1


