## CHILD PLAY - INSTALL POSTGRESQL STANDALONE ##
- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: no
  tasks:

    - debug:
        var: pg_rpms

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: config-os-user
      tags: config-os-user

#    - import_role:
#        name: prep-dirs
#      tags: prep-dirs

#    - import_role:
#        name: postgresql-params
#      tags: postgresql-params

# postgres automation - 
# 1. disable transparent hugepages (?)
# 2. install rpms
# 3. change user definitions - including bash profile
# 4. prep dirs V
# 5. change systemd postgres service
# 6. initdb --data-checksums
# 7. postgresql.conf params
# 8. pg_hba.conf
# 9. adding pg_stat_statement, postgis extentions
# 10. change tablespace of template 1

