## CHILD PLAY - INSTALL POSTGRESQL STANDALONE ##
- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: no
  tasks:

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: cfg-os-user
      tags: cfg-os-user

    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - name: Initiate Cluster
      command: "/usr/pgsql-{{ pg_major_version }}/bin/initdb --pgdata {{ pg_data }} --data-checksums"
      become_user: "{{ pg_os_user }}"
      tags: initdb

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv

#    - import_role:
#        name: pg-std-prms
#      tags: pg-std-prms

# postgres standalone automation - 
# 1. install rpms V
# 2. change user definitions - including bash profile V
# 3. prep dirs V
# 4. change systemd postgres service V
# 5. initdb --data-checksums V
# 6. postgresql.conf params
# 7. pg_hba.conf
# 8. adding pg_stat_statement, postgis extentions
# 9. change tablespace of template 1


