- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: yes
  tasks:

    - import_role:
        name: no-selinux
      tags: no-selinux 

    - import_role:
        name: cfg-hosts-file
      tags: cfg-hosts-file
      when: pg_type == "REPLICA"

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: cfg-os-user
      tags: cfg-os-user

    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv

    - import_role:
        name: add-known-hosts
      vars:
        known_hosts: "{{ (ansible_play_batch|map('extract', \
                                                  hostvars, \
                                                  ['ansible_eth0', 'ipv4', 'address'])|list) + 
                          ansible_play_batch }}"
      become_user: "{{ pg_os_user }}"
      tags: add-known-hosts

# ssh keys - not include backup server

