- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: yes
  tasks:

    - import_role:
        name: no-selinux
      tags: no-selinux 

    - import_role:
        name: cfg-hosts-file
      tags: cfg-hosts-file
      when: pg_type == "REPLICA"

    - import_role:
        name: inst-rpms
      vars:
        repos: "{{ pg_repos }}"
        rpms: "{{ pg_rpms }}"
      tags: inst-rpms

    - import_role:
        name: cfg-os-user
      tags: cfg-os-user

    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv

# ssh keys - not include backup server

