- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  any_errors_fatal: yes
  gather_facts: yes
  tasks:

    - import_role:
        name: cfg-no-selinux
      tags: cfg-no-selinux

    - import_role:
        name: cfg-pg-os-user
      tags: cfg-pg-os-user

    - import_role:
        name: cfg-hosts-file
      when: pg_type == "REPLICA"
      tags: cfg-hosts-file

    - import_role:
        name: add-known-hosts
      when: pg_type == "REPLICA"
      become_user: "{{ pg_os_user }}"
      tags: add-known-hosts

    - name: "Setting the parameter of the hosts and user for the ssh-nopass"
      set_fact:
        dest_hosts_users_nopass: "{{ dest_hosts_users_nopass|default([]) + \
                                     [{ 'host': item, 'user': pg_os_user }] }}"
      loop: "{{ ansible_play_batch }}"
      when: pg_type == "REPLICA"
      tags: cfg-ssh-nopass

    - import_role:
        name: cfg-ssh-nopass
      when: pg_type == "REPLICA"
      become_user: "{{ pg_os_user }}"
      tags: cfg-ssh-nopass
   
    - import_role:
        name: prep-dirs
      tags: prep-dirs

    - import_role:
        name: inst-pg-rpms
      tags: inst-pg-rpms

    - import_role:
        name: inst-psycopg
      tags: inst-psycopg

    - import_role:
        name: cfg-pg-srv
      tags: cfg-pg-srv


