# this module change the parameters with alter system - which change the postgresql.auto.conf
 - name: "changing the pg parameters in postgresql.auto.conf"
   postgresql_set:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
   loop: "{{ pg_stat_statement_params + pg_stat_statement_extra_params }}"
   become_user: "{{ pg_os_user }}"
   environment:
     PGDATA: "{{ pg_data }}"
   tags: pg-stat-statement-params

- name: Adding the extenstion to postrges db
  postgresql_ext:
    name: "pg_stat_statement"
    state: present
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
  tags:
    - pg_extentions
