# remote user to connect to - need to be sudoer
rmt_user: dba

# postgresql os user
pg_os_user: postgres

# full pg version to install 
pg_full_version: "{{ version }}"

# pg_major_version
pg_major_version: "{{ ((pg_full_version|string).split('.'))[0] }}"

# pg binaries location
pg_bin: "/usr/pgsql-{{ pg_major_version }}/bin"

# general pg directory
postgresql_dir: "/postgres"

# base pg dir for this version
base_dir: "{{ postgresql_dir }}/{{ pg_major_version }}"

# pg tablespaces directory
pg_tbs: "{{ base_dir }}/tbs"

# pg database main directory
pg_data: "{{ base_dir }}/data"

# pg replica recovering wals directory
pg_wals_from_pri: "{{ base_dir }}/wals_from_primary"

# pg directories to create
dirs_info:
  - path: "{{ postgresql_dir }}"
    mode: "0774"
    owner: "{{ pg_os_user }}" 
  - path: "{{ base_dir }}"
    mode: "0774"
    owner: "{{ pg_os_user }}"
  - path: "{{ pg_data }}"
    mode: "0700"
    owner: "{{ pg_os_user }}"
  - path: "{{ pg_tbs }}"
    mode: "0700"
    owner: "{{ pg_os_user }}"
  - path: "{{ pg_wals_from_pri }}"
    mode: "0700"
    owner: "{{ pg_os_user }}"

# pg service name
pg_srv_name: "postgresql-{{ pg_major_version }}.service"

# vg name for pg
fs_vg: vgpg

# lv name for pg 
fs_lv: pglv

# pg database
pg_db: "postgres"

# pg admin user
pg_admin_user: "postgres"

# vaultPass, postgres-pass
# create with:
# ansible-vault encrypt_string 'postgres-pass' --name admin_user_pass
# need to put postgres md5 hash instead - no!!! md5 is hackable 
admin_user_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35666633623939303434323138396666656164366337393562353331383564323730626665613437
          3264633761616432393432383261666564623866663938350a323565663965643934303465643036
          31323166633666373863306330326562633866633933333665333831343538353565386636373139
          3761326635623562380a666338616463646130643861383635343833313364323330313031613831
          6563

# true to add postgis extention
# false to not add postgis extention
postgis: no

postgis_extention: 
  extention: "postgis"
  database: "{{ app_db_name }}"

pg_stat_statement_extention:
  extention: "pg_stat_statements"
  database: "{{ pg_db }}"
  restart_params:
    - name: "shared_preload_libraries"
      value: "pg_stat_statements"
  reload_params:
    - name: "pg_stat_statements.max"
      value: "1000"
    - name: "pg_stat_statements.track"
      value: "all"

extentions_info: "{{ [pg_stat_statement_extention] + \
                     (postgis|ternary([postgis_extention], [])) }}"

rep_user_name: replicator

# Need to change when moving to real place.
# created using:
# ansible-vault encrypt_string 'postgres-pass' --name rep_user_pass
rep_user_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38323832613464396432633465366661633865353030316537353964313336386266336530646164
          3530663139643836326537643661383465373262393864390a393536346335663031373535666132
          33393336396539613438626233366564323130613531663133306338613833623063393264636337
          6462326533356366380a613664636533643636343935353362323236636563616336323338326239
          3435

required_params:
  - "cluster_name"
  - "version"
  - "pg_type" # REPLICA / STANDALONE
  - "app_db_name" 
  - "app_user_name" 
  - "app_user_pass"

replica_required_params:
  - "primary_host"

