## CHILD PLAY - INSTALL POSTGRESQL STANDALONE ##
- hosts: "{{ primary_host|default(cluster_name) }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  gather_facts: no
  tasks:

    - import_role: 
        name: cre-pg-clu
      tags: cre-pg-clu

    - import_role:
        name: cre-default-tbs
      tags: cre-default-tbs

    - import_role:
        name: cfg-basic-standarts
      tags: cfg-basic-standarts

    - import_role:
        name: cre-app-db
      become_user: "{{ pg_os_user }}"
      environment:
        PGDATA: "{{ pg_data }}"
      tags: cre-app-db

    - import_role:
        name: add-extentions
      tags: add-extentions

