- hosts: "{{ cluster_name }}"
  remote_user: "{{ rmt_user }}"
  become: yes
  any_errors_fatal: yes
  gather_facts: no
  tasks:

    - name: "getting postgres replication info"
      postgresql_info:
        filter: replications
      register: pg_info
      when: inventory_hostname == primary_host
      become_user: "{{ pg_os_user }}"
      tags: chk-rep

    - name: setting parameter as the list of the replicated hosts
      set_fact:
        replicated_hosts: "{{ hostvars[primary_host].pg_info.replications.values() \
                              | map(attribute='client_hostname') \
                              | list }}"
      tags: chk-rep

    - name: "Create replication user"
      postgresql_user:
        db: "{{ pg_db }}"
        name: "{{ rep_user_name }}"
        password: "{{ rep_user_pass }}"
        role_attr_flags: "REPLICATION" #"SUPERUSER" # change to REPLICATION ?
      become_user: "{{ pg_os_user }}"
      environment:
        PGDATA: "{{ pg_data }}"
      when: inventory_hostname == primary_host
      tags: rep-user

    - name: "Make sure standby is down before the sync"
      systemd:
        name: "{{ pg_srv_name }}"
        state: stopped
      when: 
        - inventory_hostname != primary_host
        - inventory_hostname not in replicated_hosts
      tags:
       - rmt-pg-bck
       - initiate-standby
       - resync-standby

    - import_role:
        name: rmt-pg-bck
      vars:
        backup_dir: "{{ pg_data }}"
        remote_host: "{{ primary_host }}"
      when: 
        - inventory_hostname != primary_host 
        - inventory_hostname not in replicated_hosts
      tags:
        - rmt-pg-bck
        - initiate-standby
        - resync-standby

    - import_role:
        role: cfg-replica
      tags: 
        - cfg-replica
        - resync-standby

    - name: "Make sure the new standby is started after the configurarion change"
      systemd:
        name: "{{ pg_srv_name }}"
        state: started
      when:
        - inventory_hostname != primary_host
        - inventory_hostname not in replicated_hosts
      tags: resync-standby

