
- name: install the psycopg required rpms
  yum:
    name: "{{ psycopg_required_rpms }}"
    disablerepo: '*'
    enablerepo: "{{ psycopg_repos }}"
    lock_timeout: 180
    state: present
  tags: psy-rpms

# when we go back - change this to mount and get from nfs maybe ??
# or to have our own installtions server with httpd and get from it everything

- name: untar the psycopg installtion files
  unarchive:
    src: "psycopg{{ psycopg_version }}.tar.gz"
    dest: "{{ tmp_loc }}"
  tags: psy-untar

- name: build the psycopg module
  command: "/usr/bin/python setup.py build"
  args:
    chdir: "{{ tmp_loc }}/psycopg{{ psycopg_version }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pg_bin }}"
  tags: psy-build

- name: install the psycopg module
  command: "/usr/bin/python {{ tmp_loc }}/psycopg{{ psycopg_version }}/setup.py install"
  args:
    chdir: "{{ tmp_loc }}/psycopg{{ psycopg_version }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pg_bin }}"
  tags: psy-build

- name: remove the installtion files
  file:
    path: "{{ tmp_loc }}/psycopg{{ psycopg_version }}"
    state: absent
  tags: psy-clean
