---
pg_os_user: "postgres"

pg_admin_user: "postgres"

checkpoint_completion_target: "0.9"
listen_addresses: "*"
track_activity_query_size: "30720"

pg_basic_reload_params:
  - name: "checkpoint_completion_target"
    value: "{{ checkpoint_completion_target }}"

pg_basic_restart_params:
  - name: "listen_addresses"
    value: "{{ listen_addresses }}"  # check when going back if it * or 0.0.0.0 
  - name: "track_activity_query_size"
    value: "{{ track_activity_query_size }}"

pg_hba_basic_records:
  - conn_type: "host"
    database: "all"
    user: "all"
    address: "0.0.0.0/0"
    auth_method: "md5"

max_shared_buffer_size_mb: 8192
...
