pg_os_user: postgres
pg_os_group: "{{ pg_os_user }}"
user_hashed_pass: '$6$3GUGQQ3W$hDgP9Iv8wGlClWF4eo2yJ1wUfvkcb50JpUpE2R8IRad6D25iJS.Ld2b9oNbO4o5wkMg/6uEcBrb.jpUPNRNzn0'
user_id: 26
group_id: 26
pg_home_dir: "/var/lib/pgsql"
user_shell: "/bin/bash"
pg_bash_profile_path: "{{ home_dir }}/.pgsql_profile"
pg_bin: "/usr/pgsql-{{ pg_major_version }}/bin"
