---
- name: "Get list of keys from each host"
  command: "ssh-keyscan {{ item }}"
  register: keys_output
  changed_when: false
  loop: "{{ known_hosts }}"

- name: "Adding the keys to known hosts"
  known_hosts:
    name: "{{ item.split(' ')[0] }}"
    hash_host: yes
    key: "{{ item }}"
  no_log: yes
  loop: "{{ keys_output.results | sum(attribute='stdout_lines', start=[]) }}"
...
