- name: Enabling the pg repo
  yum_repository:
    baseurl: "{{ pg_repo_info.base_url }}"
    name: "{{ pg_repo_info.name }}"
    file: "{{ repos_file_name }}" 
    description: "{{ pg_repo_info.desc }}"
    enabled: yes
    gpgcheck: no
  tags: add-repos

- name: Install the postgres rpms
  yum:
    name: "{{ item.rpms }}"
    disablerepo: "*"
    enablerepo: "{{ item.repos }}"
    state: present
    update_cache: true
    lock_timeout: 180
  loop:
    - { rpms: "{{ pg_rpms }}", repos: "{{ pg_repo_info.name }}" }
    - { rpms: "{{ python_postgres_rpms }}", repos: "{{ python_postgres_repos }}"} 
  tags: inst-rpms

- name: Install the postgis rpms
  yum:
    name: "{{ postgis_rpms }}"
    disablerepo: "*"
    enablerepo: "{{ postgis_repos }}"
    state: present
    update_cache: true
    lock_timeout: 180
  when: postgis|bool
  tags: inst-rpms
