rmt_user: dba

os_user: postgres

base_dir: "/postgres/10"

pg_tbs: "{{ base_dir }}/tbs/app_tbs"

pg_data: "{{ base_dir }}/data"

dirs_info:
  - { "path": "{{ base_dir }}", "mode": "0644", "owner": "{{ pg_os_user }}" }
  - { "path": "{{ pg_data }}", "mode": "0644", "owner": "{{ pg_os_user }}" }
  - { "path": "{{ pg_tbs }}", "mode": "0644", "owner": "{{ pg_os_user }}" }

replication_wal_dir: { "path": "{{ pg_base }}/wals_from_primary", "mode": "0644", "owner": "{{ pg_os_user }}"  }

fs_vg: vgpg

fs_lv: pglv

pg_full_version: 10.7

pg_major_version: "{{ ((pg_full_version|string).split('.'))[0] }}"
 
pg_repos:
  - { "name": "pg{{ pg_major_version }}", "base_url": "file:///rpm/10/redhat/pg10", "desc": "Postgresql Repo - version {{ pg_major_version }}" }


pg_rpms:
  - "postgresql{{ pg_major_version }}-libs-{{ pg_full_version }}"
  - "postgresql{{ pg_major_version }}-server-{{ pg_full_version }}"
  - "postgresql{{ pg_major_version }}-contrib-{{ pg_full_version }}"
  - "pg_top{{ pg_major_version }}"
  - "pgcenter"
