---
- name: "creating the tablespace directory"
  file:
    path: "{{ def_tbs_dir }}"
    state: directory
    mode: "0700"
  become_user: "{{ pg_os_user }}"
  tags: new-tbs

- name: "defining the new tablespace"
  postgresql_tablespace:
    tablespace: "{{ default_tablespace }}"
    location: "{{ def_tbs_dir }}"
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
  tags: new-tbs

- name: "changing the pg default tablespace parameter in postgresql.auto.conf"
  postgresql_set:
    name: "default_tablespace"
    value: "{{ default_tablespace }}"
  notify: Reload pg
  tags: def-tbs

#
## THIS TASK WILL WORK FOR ANSIBLE 2.9
## AT THIS TIME WE HAVE 2.8.
## IF YOU SEE THIS AND WE HAVE ANSIBLE >= 2.9
## PLEASE REMOVE THE TASKS THAT DOES THIS AND REMOVE THE # FROM THIS TASK
## THANKS. DATE: 3.2.2020
#
#- name: "changing the givin databases to the new tablespace"
#  postgresql_db:
#    db: "{{ template_db }}"
#    tablespace: "{{ default_tablespace }}"
#  become_user: "{{ pg_os_user }}"
#  environment:
#    PGDATA: "{{ pg_data }}"
#  tags: change

- name: "check template db tablespace"
  postgresql_query:
    query: SELECT t.spcname as "tablespace" 
           FROM pg_catalog.pg_database d 
           JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid 
           WHERE d.datname = %(template)s
    named_args:
      template: "{{ template_db }}"
  register: tablespace_check
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
  tags: def-tbs

# not using the postgresql_query because it can not handle identifiers
- name: "changing the given databases to the new tablespace"
  command: "{{ pg_bin }}/psql -c 'alter database \"{{ template_db }}\" set tablespace \"{{ default_tablespace }}\";'"
  when: default_tablespace != tablespace_check.query_result[0].tablespace
  become_user: "{{ pg_os_user }}"
  environment:
    PGDATA: "{{ pg_data }}"
  tags: def-tbs
...
