- name: "changing the pg parameters in postgresql.conf"
  lineinfile:
    path: "{{ pg_data }}/postgresql.conf"
    insertafter: "^(#{{ item.name }}=|#{{ item.name }} =|# {{ item.name }}=|# {{ item.name }} =)"
    regexp: "^({{ item.name }}=|{{ item.name }} =)"
    line: "{{ item.name }} = {{ item.value }}"
  loop: "{{ pg_params }}"
  tags: postgresql-params

- name: "adding the connection needed to pg_hba.conf"
  lineinfile:
    path: "{{ pg_data }}/pg_hba.conf"
    regexp: "{{ item.conn_type }}         {{ item.database }}     {{ item.user }}         {{ item.address }}      {{ item.auth_method }}"
    line: "{{ item.conn_type }}         {{ item.database }}     {{ item.user }}         {{ item.address }}      {{ item.auth_method }}"
  loop: "{{ pg_hba_params }}"
  tags: pg-hba-params

